export const dummyTemplates = [
  {
    id: 1,
    imgSrc: "/images/templates/temp1.jpg",
    name: "First Template",
    price: "30.44",
    oldPrice: "300.4",
    percerntageOff: "40",
  },
  {
    id: 2,
    imgSrc: "/images/templates/temp2.jpg",
    name: "Second Template",
    price: "30.44",
    oldPrice: "300.4",
    percerntageOff: "40",
  },
  {
    id: 3,
    imgSrc: "/images/templates/temp3.jpg",
    name: "Third Template",
    price: "30.44",
    oldPrice: "300.4",
    percerntageOff: "40",
  },
  {
    id: 4,
    imgSrc: "/images/templates/temp4.jpg",
    name: "Fourth Template",
    price: "30.44",
    oldPrice: "300.4",
    percerntageOff: "40",
  },
  {
    id: 5,
    imgSrc: "/images/templates/temp5.jpg",
    name: "Fifth Template",
    price: "30.44",
    oldPrice: "300.4",
    percerntageOff: "40",
  },
];
